### ISSUE TITLE
timers, recordsモデルを作成

### ISSUE THREAD

**Issue by fuurin** [fuurin/cumulative_timer#15]
以下のテーブルと、それぞれに対応するrustのモデルを作成

timersテーブル
- id: serial, primary key
- user_id: integer references users(id), not null
- name: varchar(255), not null, unique

create index on timers
- user_id
- name

recordsテーブル
- id: serial primary key
- timer_id: integer references timers(id), not null
- start_at: timestamp(0) with time zone, not null
- end_at: timestamp(0) with time zone, not null
- duration: integer, not null

timestampは最小単位を秒とするため、小数点以下は0桁に設定
参考：https://www.postgresql.jp/document/9.4/html/datatype-datetime.html

create index on records
- timer_id
- timer_id, start_at, end_at (範囲指定クエリ用, 本当にインデックスしてくれる？)

**Comment by noimin0610** [comment]
duration に CHECK 制約 (duration >= 0) を入れると良さげ

**Comment by noimin0610** [comment]
primary key 制約がついた列については postgresql が勝手にインデックスを作ってくれる
